"""empty message

Revision ID: 478512f92728
Revises: None
Create Date: 2016-09-21 22:47:55.649011

"""

# revision identifiers, used by Alembic.
revision = '478512f92728'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direction_body', sa.Column('full_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direction_body', 'full_name')
    ### end Alembic commands ###
